Hostel_Room_Booking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.http import HttpResponse
from accounts.views import default_home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', default_home, name='default_home_name'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.url')),
    path('student/', include('hostelapp.url')),
    path('cheif_warden/', include('cheif_warden.url')),
    path('warden/', include('Wardenapp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Wardenapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('floors/<str:pk>', views.floors_view, name='warden_floor1'),
    path('blocks/', views.blocks_view, name='warden_blocks'),
    path('rooms/<str:pk>', views.rooms_view, name='warden_rooms'),
    path('room/student/list/<str:pk>',views.student_view,name='student_rooms_info')

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator

# Create your models here.

GENDER_CHOICES = [
    ('Male', 'Male'),
    ('Female', 'Female')
]


class CustomUser(AbstractUser):
    Gender = models.CharField(max_length=6, choices=GENDER_CHOICES)
    matric = models.CharField(max_length = 20, default = 'LCU/')
    DOB = models.DateField(max_length=8, blank=True,null=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)  # validators should be a list

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.contrib.auth.forms import UserCreationForm
from .form import CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .decorators import unauthenticated_user
from django.contrib.auth.models import Group
import re


# Create your views here.

def hello_world(request):
    return HttpResponse(f"<h3>Hello {request.user}!</h3>")


@unauthenticated_user
def login_views(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('default_home_name')
            # return HttpResponse(f'hello {request.user}')
        else:
            messages.info(request, "username or password is incorrect")
    context = {}
    return render(request, 'accounts/loginPage.html', context)


@unauthenticated_user
def register_views(request):
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # form.save()
            user = form.save(commit=False)
            user.save()
            user_email = form.cleaned_data.get('email')
            students = re.findall('students', user_email)
            warden = re.findall('warden', user_email)
            print(user_email, type(user_email), '--------------------------')
            print('students' in students)
            if 'students' in students:
                # print('hello student')
                user_group = Group.objects.get(name='student')
                user.groups.add(user_group)
            elif 'warden' in warden:
                # print('hello warden')
                user_group = Group.objects.get(name='warden')
                user.groups.add(user_group)
            else:
                print('error')
                messages.error(request, 'its not a correct email!')
                messages.error(request, 'It should contain username@students.lcu.edu!')
                user.delete()
                return redirect('register_page')
            user_name = form.cleaned_data.get('username')
            # print(user_name)
            messages.success(request, 'Account was successfully created for ' + user_name)
            return redirect('login_page')
    context = {'form': form}
    return render(request, 'accounts/registerPage.html', context)


def logout_view(request):
    logout(request)
    messages.success(request, 'You are successfully logged out')
    return redirect('login_page')


def default_home(request):
    print('default_home')
    group = None
    if request.user.is_anonymous:
        return redirect('login_page')
    else:
        if request.user.groups.exists():
            group = request.user.groups.all()[0].name
            print(group)

            if group == 'student':
                return redirect('home')

            elif group == 'warden':
                return redirect('warden_blocks')
                # return view_func(request, *args, **kwargs)
            elif group == 'chief warden':
                return redirect('cheif_warden_home')
            else:
                message = "You are not authorized to view this page"
                messages.error(request, message)
                return redirect('logout_page')
                # return HttpResponse('You are not authorized to view this page')

accounts/templates/accounts/loginPage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/LCU.jpg'%}" type="image/x-icon">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">

    <title>Login - Hostel Management Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
       body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
           background-image:url("{% static 'img/bg.jpg'%}");
      background-size: cover;
      background-repeat: no-repeat;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #fff;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            /*color: #fff;*/
            font-size: 20px;
            font-weight: bolder;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #33ccff !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
    </style>

</head>
<body>
                <!-- <h3 id="form-title"> LOGIN</h3> -->
<div class="container h-100">


    <div class="d-flex justify-content-center h-100">
    

        <div class="user_card">
    

            <div class="d-flex justify-content-center">

<img src="{% static 'img/LCU.jpg'%}" align="center" width="70" height="70" class="rounded-circle">
<br />

            </div>
            <h3 id="form-title" align="center">LOGIN HERE</h3>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>

                        <input type="text" name="username" placeholder="Username..." class="form-control">
                    </div>

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>

                        <input type="password" name="password" placeholder="Password..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Login">
                    </div>
                </form>

            </div>

            {% for message in messages %}
                 <div class="btn-warning" style="padding: 10px;
            margin-top: 10px; color: #fff; border: 5px;">
                <p id="messages">{{ message }}</p>
            </div>
            {% endfor %}

           <!--  <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Don't have an account? <a href="{% url 'register_page' %}" class="ml-2">Sign Up</a>
                </div>

            </div> -->
        </div>
    </div>
</div>
</body>

</html>

accounts/templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/LCU.jpg'%}" type="image/x-icon">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">

    <title>Hostel Management Portal Registration</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        *{
            margin: 0;
            padding: 0;
        }

        body
      {

           background-image:url("{% static 'img/bg.jpg'%}");
      background-size: cover;
      background-repeat: no-repeat;
      background-position-y: 30%;
      background-position-x:30%;
      height: auto;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: white;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

        #form-title {
            /*color: #fff;*/
        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #f7ba5b !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        #messages {
            background-color: grey;
            color: #fff;
            padding: 10px;
            margin-top: 10px;
        }
footer{
    background-color:black;
    height:9vh;
    color:white;
}
    </style>

</head>

<body>

   
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">CREATE ACCOUNT</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>

                   <!--     <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-phone"></i></span>
                        </div>
                        {{ form.phone_number }}
                    </div> -->

<!-- 
<div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.phone_number }}
                    </div>
 -->

                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>


                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>

                </form>
            </div>


            <div>
                {% if form.errors %}
                    <p id="messages">{{ form.errors }}</p>
                {% endif %}
                {% for message in messages %}
                    <p id="messages">{{ message }}</p>
                {% endfor %}
            </div>

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'Email..';
    form_fields[3].placeholder = 'Enter password...';
    form_fields[4].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>



</body>
</html>


accounts/templates/accounts/registerPage.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <link rel="shortcut icon" href="{% static 'img/LCU.jpg'%}" type="image/x-icon">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta charset="utf-8">

    <title>Register Here - Hostel Management Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <style>
        body,
        html {
            margin: 0;
            padding: 0;
            height: 100%;
           background-image:url("{% static 'img/bg.jpg'%}");
      background-size: cover;
      background-repeat: no-repeat;
        }

        .user_card {
            width: 350px;
            margin-top: auto;
            margin-bottom: auto;
            background: #fff;
            position: relative;
            display: flex;
            justify-content: center;
            flex-direction: column;
            padding: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
            border-radius: 5px;

        }

        .form_container {
            margin-top: 20px;
        }

               #form-title {
            /*color: #fff;*/
            font-size: 20px;
            font-weight: bolder;

        }

        .login_btn {
            width: 100%;
            background: #33ccff !important;
            color: white !important;
        }

        .login_btn:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

        .login_container {
            padding: 0 2rem;
        }

        .input-group-text {
            background: #33ccff !important;
            color: white !important;
            border: 0 !important;
            border-radius: 0.25rem 0 0 0.25rem !important;
        }

        .input_user,
        .input_pass:focus {
            box-shadow: none !important;
            outline: 0px !important;
        }

      

    </style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">

             <div class="d-flex justify-content-center">

<img src="{% static 'img/LCU.jpg'%}" align="center" width="70" height="70" class="rounded-circle">
<br />

            </div>
            <h3 id="form-title" align="center">Create Account</h3>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        {{ form.email }}
                    </div>

                     <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-id-card"></i></span>
                        </div>
                        {{ form.matric }}
                    </div>

                       <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-phone"></i></span>
                        </div>
                        {{ form.phone_number }}
                    </div>


                <!--        <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                        </div>
                        <input type="date" name="DOB" id="id_DOB" required>
                    </div>


                       <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.Gender }}
                    </div>
 -->
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>


                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Register Account">
                    </div>

                </form>
            </div>


            
                {% if form.errors %}
                <div class="btn-warning" style="padding: 10px;
            margin-top: 10px; color: #fff; border: 5px;">
                    <p id="messages" >{{ form.errors }}</p>
                        </div>
                {% endif %}
<br />
                {% for message in messages %}
                 <div class="btn-warning" style="padding: 10px;
            margin-top: 10px; color: #fff">
                    <p id="messages">{{ message }}</p>
                        </div>
                {% endfor %}
        

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'login_page' %}" class="ml-2">Login</a>
                </div>
            </div>

        </div>
    </div>
</div>
<script>
    /* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
*/

    //Query All input fields
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder = 'Username..';
    form_fields[2].placeholder = 'username@students.lcu.edu';
    form_fields[4].placeholder = '+234';    
    form_fields[5].placeholder = 'Enter password...';
    form_fields[6].placeholder = 'Re-enter Password...';


    for (var field in form_fields) {
        form_fields[field].className += ' form-control'
    }
</script>
</body>
</html>